version: '3.9'

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db 
  
  # app:
  #   image: harshkumarupadhyay/nodetesting:v01
  #   ports:
  #     - 5001:5001
  #   environment:
  #     PORT: 5001
  #     MONGODB_URL: mongodb://mongo_db:27017
  #   depends_on:
  #     - mongo_db

volumes:
  mongo_db: {}
